url: https://easyprivacy.tech
baseurl: ""

# Site settings
title: Easy Privacy
email: contact@datatransition.net
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Laure Isabelle LIGAUDAN
  pic: laure-isabelle-ligaudan
  position: Spécialiste Privacy depuis 2004
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/laure-isabelle-ligaudan-12834019/
    - title: twitter
      url: https://twitter.com/lilconseil

- name: Michael FOZEU
  pic: michael-fozeu
  position: Designer de transition
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/michaelfozeu/
    - title: twitter
      url: https://twitter.com/mfozeu

- name: Glenn ROLLAND
  pic: glenn-rolland
  position: Expert systèmes et réseaux
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/glenux/
    - title: twitter
      url: https://twitter.com/glenux

- name: Raphaël RAULT
  pic: raphael-rault
  position: Avocat spécialisé Privacy
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/rrault/?ppe=1

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/easy_privacy


# Postal address (add as many lines as necessary)
address:
  - line: Fécamp
  - line: Fécamp

# Build settings
markdown: kramdown
permalink: pretty
