url: https://datatransition.github.io/easyprivacy-site-static/
baseurl: ""

# Site settings
title: Easy Privacy
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Laure Isabelle LIGAUDAN
  pic: 1
  position: Spécialiste Privacy since 2004


- name: Michael FOZEU
  pic: 2
  position: Designer de transition
  social:
    - title: twitter
      url: https://twitter.com/mfozeu
    - title: linkedin
      url: https://www.linkedin.com/in/michaelfozeu/

- name: Glenn ROLLAND
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/glenux
    - title: linkedin
      url: https://www.linkedin.com/in/glenux/
    - title: github
      url: https://github.com/glenux

- name: Raphaël RAULT
  pic: 4
  position: Avocat spécialisé Privacy
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/rrault/?ppe=1

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/easy_privacy


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
permalink: contact
